services:
  neptunus:
    build: .
    ports:
      - "9100:9100"
      - "9600:9600"
    restart: always
    volumes:
      - ./.pipelines/:/etc/neptunus/conf/pipelines
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
    logging:
      options:
        max-size: "200m"
        max-file: "3"