version: 3

includes:
  generics: generics.yml

vars:
  NEPTUNUS_BUILD_VERSION:
    sh: git log -n 1 --format=%h

tasks:
  generate-notice-file:
    aliases: [ notice ]
    cmds:
    - task: generics:notice

  build-linux-amd64:
    cmds:
    - task: generics:build
      vars:
        NEPTUNUS_BUILD_GOOS: linux
        NEPTUNUS_BUILD_GOARCH: amd64

  build-windows-amd64:
    cmds:
    - task: generics:build
      vars:
        NEPTUNUS_BUILD_GOOS: windows
        NEPTUNUS_BUILD_GOARCH: amd64

  pack-linux-amd64:
    cmds:
    - task: generics:tar
      vars:
        NEPTUNUS_BUILD_GOOS: linux
        NEPTUNUS_BUILD_GOARCH: amd64

  pack-windows-amd64:
    cmds:
    - task: generics:zip
      vars:
        NEPTUNUS_BUILD_GOOS: windows
        NEPTUNUS_BUILD_GOARCH: amd64

# global tasks
  build:
    cmds:
    - task: build-linux-amd64
    - task: build-windows-amd64

  pack:
    cmds:
    - task: pack-linux-amd64
    - task: pack-windows-amd64
