version: 3

includes:
  generics: generics.yml

vars:
  NEPTUNUS_BUILD_VERSION:
    sh: git log -n 1 --format=%h

tasks:
  generate-notice-file:
    cmds:
    - task: generics:notice

  build-linux-amd64:
    vars:
      NEPTUNUS_BUILD_GOOS: linux
      NEPTUNUS_BUILD_GOARCH: amd64
    cmds:
    - task: generics:build
    - task: generics:zip

  build-windows-amd64:
    vars:
      NEPTUNUS_BUILD_GOOS: windows
      NEPTUNUS_BUILD_GOARCH: amd64
    cmds:
    - task: generics:build
    - task: generics:tar
