version: 3

includes:
  generics: Taskfile.generics.yaml
  build: Taskfile.build.yaml
  pack: Taskfile.pack.yaml

vars:
  NEPTUNUS_BUILD_DIR: "builds"
  NEPTUNUS_BUILD_VERSION:
    sh: echo "$(git describe --abbrev=0 --tags)-$(git log -n 1 --format=%h)"

tasks:
  default:
    silent: true
    cmds:
      - task --list --color

  cleanup:
    desc: Cleanup after build
    cmds:
    - task: generics:cleanup

  all:
    desc: Build and pack all binaries
    cmds:
    - task: build:tests
    - task: build:linux-amd64
    - task: build:linux-arm64
    - task: build:windows-amd64
    - task: build:windows-arm64
    - task: build:darwin-amd64
    - task: build:darwin-arm64
    - task: build:notice
    - task: pack:linux-amd64
    - task: pack:linux-arm64
    - task: pack:windows-amd64
    - task: pack:windows-arm64
    - task: pack:darwin-amd64
    - task: pack:darwin-arm64
