package processors

import (
	_ "github.com/gekatateam/neptunus/plugins/processors/clone"
	_ "github.com/gekatateam/neptunus/plugins/processors/converter"
	_ "github.com/gekatateam/neptunus/plugins/processors/deduplicate"
	_ "github.com/gekatateam/neptunus/plugins/processors/defaults"
	_ "github.com/gekatateam/neptunus/plugins/processors/delete"
	_ "github.com/gekatateam/neptunus/plugins/processors/drop"
	_ "github.com/gekatateam/neptunus/plugins/processors/dynamic_template"
	_ "github.com/gekatateam/neptunus/plugins/processors/exec"
	_ "github.com/gekatateam/neptunus/plugins/processors/http"
	_ "github.com/gekatateam/neptunus/plugins/processors/line"
	_ "github.com/gekatateam/neptunus/plugins/processors/log"
	_ "github.com/gekatateam/neptunus/plugins/processors/mixer"
	_ "github.com/gekatateam/neptunus/plugins/processors/parser"
	_ "github.com/gekatateam/neptunus/plugins/processors/redis"
	_ "github.com/gekatateam/neptunus/plugins/processors/regex"
	_ "github.com/gekatateam/neptunus/plugins/processors/rk"
	_ "github.com/gekatateam/neptunus/plugins/processors/sql"
	_ "github.com/gekatateam/neptunus/plugins/processors/starlark"
	_ "github.com/gekatateam/neptunus/plugins/processors/stats"
	_ "github.com/gekatateam/neptunus/plugins/processors/template"
	_ "github.com/gekatateam/neptunus/plugins/processors/through"
)
