[settings]
  id = "test.pipeline.2"
  lines = 5
  run = true #
  buffer = 100

[[inputs]]
  [inputs.httpl]
    address = ":9300"
  [inputs.httpl.parser]
    type = "json"
  [inputs.httpl.filters.glob]
    alias = "t4"

[[processors]]
  [processors.line]

[[processors]]
  [processors.drop]
    [processors.drop.filters.glob.labels]
      "::line" = ["4"]

[[processors]]
  [processors.log]
    level = "warn"
    [processors.log.serializer]
      type = "json"
      data_only = false

[[outputs]]
  [outputs.grpc]
    address = "localhost:5800"
    procedure = "stream"
    max_attempts = 5
    sleep = "2s"
    buffer = 100
  [outputs.grpc.serializer]
    type = "json"
    data_only = true
