[settings]
  id = "test.pipeline.redisproc"
  lines = 5
  run = true
  buffer = 1_000
  log_level = "debug"

[vars]
  hset = "testspace:map"

[[keykeepers]]
  [keykeepers.self]
    alias = "self"

[[inputs]]
  [inputs.http]
    address = ":9100"
    max_connections = 10
    tls_enable = false
    tls_key_file = '.testcerts\server-key.pem'
    tls_cert_file = '.testcerts\server-cert.pem'
    tls_allowed_cacerts = [ '.testcerts\ca-cert.pem' ]
  [inputs.http.parser]
    type = "json"

[[processors]]
  [processors.redis]
    log_level = "debug"
    servers = [ "localhost:6379" ]
    password = "redis"
    retry_attempts = 1
    conns_max_open = 5
    conns_max_idle = 5
    result_to = "result"
    commands = [
      [ "hset", "@{self:vars.hset}", "{{- data -}}" ],
      [ "hexpire", "@{self:vars.hset}", "{{- ttl -}}", "fields", "{{- keysnum -}}", "{{- keys -}}" ],
    ]

[[processors]]
  [processors.redis]
    servers = [ "localhost:6379" ]
    password = "redis"
    retry_attempts = 1
    conns_max_open = 5
    conns_max_idle = 5
    result_to = "afterGet"
    commands = [
      [ "hgetall", "@{self:vars.hset}" ],
    ]

[[outputs]]
  [outputs.log]
    level = "info"
    [outputs.log.serializer]
      type = "json"
      data_only = false
