[settings]
  id = "test.pipeline.2"
  lines = 5
  run = false
  buffer = 100

[[inputs]]
  [inputs.httpl]
    address = ":9200"
  [inputs.httpl.parser]
    type = "json"
  [inputs.httpl.filters.pass]
    alias = "t4"

[[processors]]
  [processors.through]
  [processors.through.filters.glob]
    routing_key = [ "http.*" ]
    alias = "t5"

[[outputs]]
  [outputs.log]
  [outputs.log.serializer]
    type = "json"
    data_only = true
  [outputs.log.filters.pass]
    alias = "t6"
