[settings]
  id = "test.pipeline.grpcoutput"
  lines = 1
  run = true
  buffer = 1_000
  log_level = "debug"


[[inputs]]
  [inputs.http]
    address = ":9200"
    max_connections = 10
    wait_for_delivery = false
    tls_enable = false
  [inputs.http.parser]
    type = "json"

[[processors]]
  [processors.rk.mapping]
    "neptunus.plugins.common.grpc.Input.SendOne" = [ "/neptunus.plugins.common.grpc.Input.SendOne" ]

[[outputs]]
  [outputs.dynamic_grpc]
    mode = "AsClient"
    proto_files = [ "./plugins/common/grpc/input.proto" ]
    [outputs.dynamic_grpc.client]
      address = "localhost:9900"
      retry_attempts = 3



