[settings]
  id = "test.pipeline.beats"
  lines = 5
  run = true
  buffer = 1_000

[[inputs]]
  [inputs.beats]

[[outputs]]
  [outputs.log]
    level = "info"
    [outputs.log.serializer]
      type = "json"
      data_only = false
    [outputs.log.filters.starlark]
      code = '''
def filter(event):
    if event.getField("from_test") < 37:
        return True
    else:
        return False
      '''

