[settings]
  id = "test.pipeline.dynamicgrpc"
  lines = 1
  run = true
  buffer = 1_000

[[inputs]]
  [inputs.dynamic_grpc]
    mode = "AsServer"
    proto_files = [ "./plugins/common/grpc/input.proto" ]
    [[inputs.dynamic_grpc.procedures]]
      name = "neptunus.plugins.common.grpc.Input.SendOne"
      invoke_response = '{}'
    [inputs.dynamic_grpc.server]
      address = ":9900"

[[outputs]]
  [outputs.log]
    level = "info"
    [outputs.log.serializer]
      type = "json"
      data_only = false
