[settings]
  id = "test.pipeline.httpproc"
  lines = 1
  run = false
  buffer = 1_000
  log_level = "debug"

[[inputs]]
  [inputs.http]
    address = ":9100"
    max_connections = 10
    wait_for_delivery = true
    tls_enable = false
    tls_key_file = '.testcerts\server-key.pem'
    tls_cert_file = '.testcerts\server-cert.pem'
    tls_allowed_cacerts = [ '.testcerts\ca-cert.pem' ]
  [inputs.http.labelheaders]
    uri = "x-uri"
    method = "x-method"
    token = "x-token"
  [inputs.http.parser]
    type = "json"
    split_array = false

[[processors]]
  [processors.http]
    host = "http://localhost:9200"
    fallbacks = [ "https://jsonplaceholder.typicode.com/posts" ]
    method = "POST"
    retry_attempts = 3
    retry_after = "1s"
    tls_enable = true
    method_label = "method"
    success_codes = [ 500 ]
    success_body = "sunt aut"
    response_body_to = "typicode.body"
    response_code_to = "typicode.code"
    [processors.http.headerlabels]
      token = "token"
    [processors.http.serializer]
      type = "json"
      data_only = false
    [processors.http.parser]
      type = "json"
      split_array = false


[[outputs]]
  [outputs.log]
    level = "info"
    [outputs.log.serializer]
      type = "json"
      data_only = false
