[settings]
  id = "test.pipeline.beats"
  lines = 5
  run = true
  buffer = 1_000

[[inputs]]
  [inputs.beats]
    ack_on_delivery = true

[[outputs]]
  [outputs.log]
    level = "info"
    [outputs.log.serializer]
      type = "json"
      data_only = false
