[settings]
  id = "test.pipeline.chanmetrics"
  lines = 2
  run = false
  buffer = 5

[[keykeepers]]
  [keykeepers.env]

[[inputs]]
  [inputs.http]
    address = ":9100"
    max_connections = 10
    query_params_to = "."
    wait_for_delivery = false
    tls_enable = false
    tls_key_file = '.testcerts\server-key.pem'
    tls_cert_file = '.testcerts\server-cert.pem'
    tls_allowed_cacerts = [ '.testcerts\ca-cert.pem' ]
    [inputs.http.parser]
      type = "json"
      split_array = true
    [inputs.http.filters.glob]
      routing_key = [ "*" ]
    [inputs.http.filters.noerrors]

[[inputs]]
  [inputs.http]
    address = ":9200"
    max_connections = 10
    query_params_to = ""
    wait_for_delivery = false
    tls_enable = false
    tls_key_file = '.testcerts\server-key.pem'
    tls_cert_file = '.testcerts\server-cert.pem'
    tls_allowed_cacerts = [ '.testcerts\ca-cert.pem' ]
    [inputs.http.parser]
      type = "json"
      split_array = false
    [inputs.http.filters.glob]
      routing_key = [ "*" ]
    [inputs.http.filters.noerrors]

[[processors]]
  [processors.rk.mapping]
    "/httpout-test-final" = [ "/httpout-test-out" ]
    "/httpout-test-out" = [ "/httpout-test-in" ]
    [processors.rk.filters.glob]
      reverse = false
      routing_key = [ "*" ]
    [processors.rk.filters.noerrors]
    [processors.rk.filters.pass]

[[outputs]]
  [outputs.log]
    level = "info"
    [outputs.log.serializer]
      type = "json"
      data_only = false
    [outputs.log.filters.glob]
      reverse = true
      routing_key = [ "/httpout-test-final" ]
    [outputs.log.filters.noerrors]
    [outputs.log.filters.pass]

[[outputs]]
  [outputs.http]
    host = "http://localhost:9200"
    batch_buffer = 100
    retry_attempts = 3
    retry_after = "1s"
    batch_interval = "1s"
    [outputs.http.filters.glob]
      routing_key = [ "/httpout-test-out" ]
    [outputs.http.serializer]
      type = "json"
      data_only = true
      mode = "array"
