[settings]
  id = "test.pipeline.beats"
  lines = 5
  run = true
  buffer = 1_000

[[inputs]]
  [inputs.beats]
    address = ":8800"
    ack_on_delivery = true

[[outputs]]
  [outputs.elasticsearch]
    servers = [ "http://localhost:9200" ]
    batch_buffer = 1_000
