[settings]
  id = "test.pipeline.exec"
  lines = 3
  run = false
  buffer = 1_000

[[inputs]]
  [inputs.cronjob]
    [[inputs.cronjob.jobs]]
      name = "healthcheck.notify"
      schedule = "@every 10s"

[[processors]]
  [processors.line]

[[processors]]
  [processors.starlark]
    code = '''
def process(event):
  args = [ "-Command", "echo '" + event.getId() + "' >> test.txt" ]
  event.delField(".")
  event.setField(".", args)
  return event
    '''

[[outputs]]
  [outputs.log]
    level = "info"
    [outputs.log.serializer]
      type = "json"
      data_only = false

[[outputs]]
  [outputs.exec]
    command = "powershell.exe"
    args = ["."]
