[settings]
  id = "test.pipeline.1"
  lines = 5
  run = true

[[inputs]]
  [inputs.httpl]
    address = ":9200"
  [inputs.httpl.parser]
    type = "json"
  [inputs.httpl.filters.pass]

[[inputs]]
  [inputs.httpl]
    address = ":9400"
  [inputs.httpl.parser]
    type = "json"
  [inputs.httpl.filters.pass]

[[processors]]
  [processors.log]
    level = "warn"
  [processors.log.serializer]
    type = "json"
    data_only = false
  [processors.log.filters.glob]
    routing_key = [ "*http.*" ]

[[processors]]
  [processors.through]

[[outputs]]
  [outputs.log]
  [outputs.log.serializer]
    type = "json"
    data_only = true
  [outputs.log.filters.pass]
