processors = []
keykeepers = []

[settings]
id = "test.pipeline.kafka.3"
lines = 5
run = false
buffer = 5
consistency = "soft"

[[inputs]]
[inputs.kafka]
enable_metrics = true
brokers = ["localhost:9092"]
client_id = "kafka-three-UPDATED"
commit_interval = "20s"
group_id = "neptunus.kafka.input"
max_uncommitted = 1e+03
start_offset = "first"
topics = ["neptunus.kafka.output"]

[inputs.kafka.parser]
type = "json"

[inputs.kafka.sasl]
mechanism = "plain"
password = "bitnami"
username = "user"

[[outputs]]
[outputs.log]
level = "warn"

[outputs.log.serializer]
data_only = false
type = "json"
