[settings]
  id = "test.pipeline.1"
  lines = 5
#  run = true #
  buffer = 1_000

[[inputs]]
  [inputs.httpl]
    address = ":9200"
    max_connections = 10
  [inputs.httpl.parser]
    type = "json"
  [inputs.httpl.filters.glob]

[[inputs]]
  [inputs.grpc]
    address = ":5800"
    [inputs.grpc.server_options]
      max_connection_idle = "5s"
      max_connection_age = "5m"
      max_connection_grace = "5s"
      inactive_transport_ping = "10s"
      inactive_transport_age = "10s"
  [inputs.grpc.parser]
    type = "json"

[[processors]]
  [processors.rk.mapping]
    "neptunus.kafka.output" = [ "/http.input.test" ]
    "neptunus.kafka.output2" = [ "/http.input.test2" ]

[[outputs]]
  [outputs.kafka]
    enable_metrics = true
    client_id = "kafka-one"
    brokers = ["localhost:9092"]
    topics_autocreate = true
    batch_timeout = "0s"
    idle_timeout = "0s"
    batch_buffer = 400
  [outputs.kafka.sasl]
    mechanism = "none"
  [outputs.kafka.headerlabels]
    input-from = "input"
  [outputs.kafka.serializer]
    type = "json"
    data_only = true
