[settings]
  id = "test.pipeline.http"
  lines = 1
  run = false
  buffer = 1_000

[[inputs]]
  [inputs.http]
    enable_metrics = true
    address = ":9100"
    max_connections = 10
    query_params_to = "."
    wait_for_delivery = true
    paths = [ "/pipelines/{id}/stop", "/pipelines/{id}/start" ]
    methods = [ "POST" ]
    path_values = [ "id" ]
    id_from = "label:id"
  [inputs.http.parser]
    type = "json"


[[processors]]
  [processors.template.fields]
    id     = '{{ .GetLabel "id" }}'
    action = '{{ with $x := split "/" .RoutingKey }}{{ $x._3 }}{{ end }}'

[[processors]]
  [processors.rk.mapping]
    "neptunus.events.pipeline" = [ "/pipelines/{id}/stop", "/pipelines/{id}/start" ]

[[outputs]]
  [outputs.log]
    level = "info"
    [outputs.log.serializer]
      type = "json"
      data_only = false
