[settings]
  id = "test.pipeline.kafka"
  lines = 5
  run = true
  buffer = 1_000

[[inputs]]
  [inputs.httpl]
    address = ":9300"
    id_from = "field:type"
  [inputs.httpl.parser]
    type = "json"
  [inputs.httpl.filters.glob]
    alias = "t4"

[[inputs]]
  [inputs.kafka]
    enable_metrics = true
    client_id = "kafka-one"
    group_id = "neptunus.kafka.input6"
    start_offset = "last"
    brokers = ["localhost:9092"]
    topics = [ "neptunus.kafka.output" ]
    commit_interval = "1s"
    max_uncommitted = 1_000
  [inputs.kafka.sasl]
    mechanism = "none"
  [inputs.kafka.parser]
    type = "json"

[[processors]]
  [processors.log]
    level = "debug"
    [processors.log.serializer]
      type = "json"
      data_only = false

[[processors]]
  [processors.rk.mapping]
    "/http.input.test" = [ "neptunus.kafka.output" ]
    "neptunus.kafka.output" = [ "/http.input.test" ]

[[outputs]]
  [outputs.kafka]
    enable_metrics = true
    client_id = "kafka-one"
    brokers = ["localhost:9092"]
    topics_autocreate = true
    idle_timeout = "0s"
    batch_buffer = 400
  [outputs.kafka.sasl]
    mechanism = "none"
  [outputs.kafka.headerlabels]
    input-from = "input"
  [outputs.kafka.serializer]
    type = "json"
    data_only = true
  [outputs.kafka.filters.glob]
    routing_key = [ "neptunus.kafka.output" ] 

[[outputs]]
  [outputs.log]
    level = "debug"
    [outputs.log.serializer]
      type = "json"
      data_only = false
  [outputs.log.filters.glob]
    routing_key = [ "/http.input.test" ]
