[settings]
  id = "test.pipeline.1"
  lines = 5
  run = true
  buffer = 1_000

[[inputs]]
  [inputs.httpl]
    address = ":9200"
    max_connections = 10
  [inputs.httpl.parser]
    type = "json"
  [inputs.httpl.filters.pass]

[[inputs]]
  [inputs.httpl]
    address = ":9400"
  [inputs.httpl.parser]
    type = "json"
  [inputs.httpl.filters.pass]

[[processors]]
  [processors.starlark]
    code = '''
def process(event):
    event.setField("new.field", 42)
    return event  
    '''

[[processors]]
  [processors.line]

[[processors]]
  [processors.log]
    level = "warn"
  [processors.log.serializer]
    type = "json"
    data_only = false
  [processors.log.filters.glob]
    routing_key = [ "*http.*" ]

[[outputs]]
  [outputs.log]
  [outputs.log.serializer]
    type = "json"
    data_only = true
    mode = "array"
  [outputs.log.filters.pass]
