[settings]
  id = "test.pipeline.httpout"
  lines = 1
  run = true
  buffer = 1_000
  log_level = "debug"

[[keykeepers]]
  [keykeepers.env]

[[inputs]]
  [inputs.http]
    address = ":9200"
    max_connections = 10
    query_params_to = "."
    wait_for_delivery = true
    tls_enable = false
    tls_key_file = '.testcerts\server-key.pem'
    tls_cert_file = '.testcerts\server-cert.pem'
    tls_allowed_cacerts = [ '.testcerts\ca-cert.pem' ]
  [inputs.http.parser]
    type = "json"
    split_array = false
    decompressor = "snappy"

[[inputs]]
  [inputs.http]
    address = ":9100"
    max_connections = 10
    query_params_to = "."
    wait_for_delivery = true
    tls_enable = false
    tls_key_file = '.testcerts\server-key.pem'
    tls_cert_file = '.testcerts\server-cert.pem'
    tls_allowed_cacerts = [ '.testcerts\ca-cert.pem' ]
  [inputs.http.parser]
    type = "json"
    split_array = false

[[processors]]
  [processors.rk.mapping]
    "/httpout-test-final" = [ "/httpout-test-out" ]
    "/httpout-test-out" = [ "/httpout-test-in" ]

[[outputs]]
  [outputs.http]
    host = "http://localhost:9200"
    retry_attempts = 3
    retry_after = "1s"
    batch_interval = "1s"
    [outputs.http.serializer]
      type = "json"
      data_only = true
      compressor = "snappy"
    [outputs.http.filters.glob]
      routing_key = [ "/httpout-test-out" ]

[[outputs]]
  [outputs.log]
    level = "info"
    [outputs.log.serializer]
      type = "json"
      data_only = false
    [outputs.log.filters.glob]
      routing_key = [ "/httpout-test-final" ]
