[settings]
  id = "test.pipeline.1"
  lines = 5
  run = true

[[inputs]]
  [inputs.http]
    address = ":9200"
  [inputs.http.filters.pass]
    alias = "t1"

[[processors]]
  [processors.log]
    level = "warn"
  [processors.log.filters.glob]
    routing_key = [ "*http.*" ]
    alias = "t2"

[[processors]]
  [processors.through]

[[outputs]]
  [outputs.log]
  [outputs.log.filters.pass]
    alias = "t3"
