[settings]
  id = "test.pipeline.dyngrpcputput"
  lines = 1
  run = true
  buffer = 1_000
  log_level = "debug"


[[inputs]]
  [inputs.http]
    address = ":9200"
    max_connections = 10
    wait_for_delivery = true
    tls_enable = false
  [inputs.http.parser]
    type = "json"

[[processors]]
  [processors.rk.mapping]
    "neptunus.plugins.common.grpc.Input.SendServerStream" = [ "/neptunus.plugins.common.grpc.Input.SendServerStream" ]

[[outputs]]
  [outputs.grpc]
    mode = "AsServer"
    proto_files = [ "./.pipelines/input.proto" ]
    [outputs.grpc.server]
      address = "localhost:8660"
      procedures = [ "neptunus.plugins.common.grpc.Input.SendServerStream" ]
      behaviour = "Broadcast"
