[settings]
  id = "test.pipeline.http"
  lines = 1
  run = false
  buffer = 1_000

[[inputs]]
  [inputs.http]
    enable_metrics = true
    address = ":9100"
    max_connections = 10
    query_params_to = "."
    wait_for_delivery = true
    paths = [ "/http.input/{uid}/push", "/http.input/{id}/put" ]
    path_values = [ "uid", "id" ]
    id_from = "label:id"
    tls_enable = false
    basic_username = "user"
    basic_password = "pass"
    tls_key_file = '.testcerts\server-key.pem'
    tls_cert_file = '.testcerts\server-cert.pem'
    tls_allowed_cacerts = [ '.testcerts\ca-cert.pem' ]
  [inputs.http.parser]
    type = "json"
    split_array = false

[[outputs]]
  [outputs.log]
    level = "info"
    [outputs.log.serializer]
      type = "json"
      data_only = false
