name: build-and-publish-artifacts
on:
  workflow_dispatch:

jobs:
  build-and-publish-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-tags: true
          fetch-depth: 0
          filter: tree:0

      - name: Setup Go 1.21.x
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.x'

      - name: Install go tools
        run: |
          go install go.elastic.co/go-licence-detector@latest
          go install github.com/go-task/task/v3/cmd/task@latest
      
      - name: Build and pack binaries
        run: |
          task -v \
            build:notice \
            build:linux-amd64 \
            build:windows-amd64 \
            pack:linux-amd64 \
            pack:windows-amd64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: archives
          path: |
            builds/*.tar.gz
            builds/*.zip
