name: build-and-publish-artifacts
on:
  workflow_dispatch:
  push:
    tags: [ "v*.*.*" ]

jobs:
  build-and-publish-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Setup Go 1.24.x
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.x'

      - name: Install go tools
        run: |
          go install go.elastic.co/go-licence-detector@latest
          go install github.com/go-task/task/v3/cmd/task@latest
      
      - name: Build and pack binaries
        run: |
          task -v \
            build:linux-amd64 \
            build:linux-arm64 \
            build:windows-amd64 \
            build:windows-arm64 \
            build:darwin-amd64 \
            build:darwin-arm64 \
            build:notice \
            pack:linux-amd64 \
            pack:linux-arm64 \
            pack:windows-amd64 \
            pack:windows-arm64 \
            pack:darwin-amd64 \
            pack:darwin-arm64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: archives
          path: |
            builds/*.tar.gz
            builds/*.zip

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          draft: true
          files: |
            builds/*.tar.gz
            builds/*.zip
