name: build-and-publish-docker-image
on:
  workflow_dispatch:
  push:
    tags: [ "v*.*.*" ]

jobs:
  build-and-publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Setup Go 1.21.x
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Install go tools
        run: |
          go install go.elastic.co/go-licence-detector@latest
          go install github.com/go-task/task/v3/cmd/task@latest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build docker image
        run: task -v build:docker

      - name: Push image
        run: |
          docker push $(docker image ls --format "{{ .Repository }}:{{ .Tag }}" | grep neptunus)
