name: run-tests
on:
  pull_request:
    types: [ opened, reopened, edited, synchronize ]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Go 1.24.x
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.x'

      - name: Install go tools
        run: |
          go install github.com/go-task/task/v3/cmd/task@latest
      
      - name: Run tests
        run: |
          task -v build:tests
